# -*- coding: utf-8 -*-
>>> # -*- coding: utf-8 -*-
... # ---------------------------------------------------------------------------
... # Clip Multiple Raster Datasets.py
... # Created on: 2017-05-06 09:26:31.00000
... # Author: Dariush Ameli (Originally generated by ArcGIS/ModelBuilder)
... # Description: 
... # ---------------------------------------------------------------------------
... 
... # Import arcpy module
... import arcpy
... 
... # Load required toolboxes
... arcpy.ImportToolbox("Model Functions")
... 
... # Local variables:
... 
... # All the raster inputs must be in a FOLDER
... RastFolder = "C:\\Azz\\RastFolder" 
... Name = "Topo.tif"
... cbd_tif = "C:\\Azz\\RastFolder\\Topo.tif"
... StateBorder = "StateBorder"
... # To avoid overwrite outputs, the Name of generated files include their input name
... Clip__Name_ = "C:\\Azz\\Clip_%Name%" 
... # Process: Iterate Rasters
... arcpy.IterateRasters_mb(RastFolder, "", "", "RECURSIVE") 
... 
... # Process: Clip
... arcpy.Clip_management(cbd_tif, "37106.4361103842 3380834.79606917 781570.283481221 4180992.8201444", Clip__Name_, StateBorder, "255", "ClippingGeometry", "MAINTAIN_EXTENT")
... 
... 
