# -*- coding: utf-8 -*-
>>> # -*- coding: utf-8 -*-
... # ---------------------------------------------------------------------------
... # ClipMultipleRasters.py
... # Created on: 2017-08-06 08:51:47.00000
... #   (generated by ArcGIS/ModelBuilder)
... # Description: 
... # ---------------------------------------------------------------------------
... 
... # Import arcpy module
... import arcpy
... 
... # Load required toolboxes. 
... arcpy.ImportToolbox("Model Functions")
... 
... 
... # Local variables:  
... RastFolder = "C:\\Azz\\RastFolder" #Raster folder is a FOLDER that contains all required reaster files.
... Name = "Topo.tif"
... cbd_tif = "C:\\Azz\\RastFolder\\Topo.tif"
... StateBorder = "StateBorder"
... Clip__Name_ = "C:\\Azz\\Clip_%Name%" #name of the output files includes name of the input rasters
... 
... # Process: Iterate Rasters
... arcpy.IterateRasters_mb(RastFolder, "", "", "RECURSIVE")
... 
... # Process: Clip
... arcpy.Clip_management(cbd_tif, "37106.4361103842 3380834.79606917 781570.283481221 4180992.8201444", Clip__Name_, StateBorder, "255", "ClippingGeometry", "MAINTAIN_EXTENT")
